Added alter_type function for PG migration
gjaldon/ecto_enum pull request #106
Opened 2020-04-21 10:10 UTC by sofakingworld

Hi! I'm little bit tired of defining migrations every time on enum change, so here i added alter_type function.

Hope it will be helpful for others :)

2020-05-11 19:07 UTC, sofakingworld commented
@gjaldon react please :3

2020-07-09 18:48 UTC, sofakingworld commented
@gjaldon would you accept this PR?

2020-10-19 01:14 UTC, gjaldon requested changes

2020-10-19 01:14 UTC, gjaldon commented on lib/ecto_enum/postgres/use.ex
> +        def alter_type() do
Hi @sofakingworld. Can we rename the function to `add_value`? `alter_type` can be a bunch of different things like renaming the type.

2020-10-20 02:24 UTC, gjaldon commented
Thanks a lot @sofakingworld 💜 🎉 💜

2020-10-20 02:24 UTC, merged